name: S&P500 Daily Scan & Publish

on:
  schedule:
    - cron: '0 22 * * 1-5'  # 22:00 UTC Mon-Fri (~5:00 PM CT)
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Download S&P500 list
        run: python download_sp500_list.py
      - name: Run worker (single)
        env:
          JOB_TOTAL: 1
          JOB_INDEX: 0
        run: python worker.py
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: raw-results-0
          path: raw-results-0.json

  aggregate_and_deploy:
    needs: worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: Finalize (aggregate & build site)
        run: python finalize.py
      - name: Show public contents
        run: |
          echo "public listing:"; ls -la public || true
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_PAT }}
          publish_dir: ./public
          commit_message: "Publish S&P500 scan site: ${{ github.run_number }}"
