name: Daily Scan & Publish (simple)

on:
  schedule:
    - cron: '0 22 * * 1-5'   # runs weekdays 22:00 UTC (adjust if needed)
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  analyze_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Download S&P500 list
        run: python download_sp500_list.py

      - name: Run worker (single)
        env:
          JOB_TOTAL: 1
          JOB_INDEX: 0
        run: python worker.py

      - name: Finalize (aggregate -> public/top_picks.json + public/data/)
        run: python finalize.py

      - name: Show public (sanity)
        run: |
          echo "public listing:"
          ls -la public || true
          echo "top_picks.json head:"
          head -n 50 public/top_picks.json || true

      - name: Deploy to gh-pages via peaceiris
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_PAT }}
          publish_dir: ./public
          commit_message: "Publish simple site — ${{ github.run_number }}"
