name: S&P500 Daily Scan & Publish (React)

on:
  schedule:
    - cron: '0 22 * * 1-5'  # 22:00 UTC Mon-Fri (adjust if desired)
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Download S&P500 list
        run: python download_sp500_list.py

      - name: Run worker
        env:
          JOB_TOTAL: 1
          JOB_INDEX: 0
        run: python worker.py

      - name: Upload worker artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: raw-results-0
          path: raw-results-0.json

  aggregate_and_build:
    needs: worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Download artifacts (worker outputs)
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Finalize & generate public/data (per-ticker JSON + archive)
        run: python finalize.py

      - name: Show generated files
        run: |
          echo "Public dir listing:"; ls -la public || true
          echo "Data files sample:"; ls -la public/data | head -n 30 || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Frontend (Vite + React + Tailwind)
        working-directory: frontend
        run: |
          # If package-lock.json exists, `npm ci` is preferred; otherwise fall back to npm install
          if [ -f package-lock.json ]; then
            echo "Found package-lock.json — running npm ci"
            npm ci
          else
            echo "No package-lock.json found — running npm install (legacy-peer-deps)"
            npm install --legacy-peer-deps
          fi
          npm run build

      - name: Show public (post-build) listing
        run: ls -la public || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_PAT }}
          publish_dir: ./public
          commit_message: "Publish S&P500 scan site: ${{ github.run_number }}"
